myproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("phenomena/", include("phenomena.urls")),
    path('admin/', admin.site.urls),
]

#when django sees include(), it removes the part of the url up to that point(so here, 'phenomena') and send the rest of the string ( here '/') to the phenomena.urls to be processed

phenomena/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path("<int:event_id>/", views.single, name="single"),
    path("", views.index, name="index"),
    path("locations/", views.locations, name="locations"),
    path("country/<str:country>/", views.country, name="country"),
    path("dates/", views.dates, name="dates"),
   
] 


# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# urlpatterns += staticfiles_urlpatterns()



#index path is phenomena/ (with nothing else). We specified this in urls.py(pathfinderproject). index is the name we give it, and the function that fires in views.py in response to a user going to that URL.
#single path is the id number of the event after phenomena (phenomena/5/)

#we bind the views.index function to "" and give it the name "index"
#we can then use the name index as a template
#remember, single is just the name we are giving it(we can also use this to link in the html) and it relates to the function single in views. The address the user is entering is phenomena/5 (or another number that is an event id)

#can add path converters. Above is int and str. Anything in <> captures that value (so you can then use it in the function)

phenomena/models.py
from django.db import models

class Event(models.Model):
    name=models.CharField(max_length=200)
    info=models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Date(models.Model):

    event=models.ForeignKey(Event, on_delete=models.CASCADE)
    date=models.DateField()
    duration=models.DurationField(null=True)

    def __str__(self):
        return str(self.date)

class Location(models.Model):

    event=models.ForeignKey(Event,on_delete=models.CASCADE)
    location=models.CharField(max_length=200,unique=True)

    def __str__(self):
        return self.location

# Create your models here.

phenomena/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Event, Location, Date

def index(request):
    #events = Event.objects.all()
    #es = ", ".join([e.name and e.info for e in events])  #ask neil to explain this
    all_events = {"events": Event.objects.all()}
    return render(request, "phenomena/index.html", all_events)
    #return HttpResponse(es)

def single(request, event_id):
    event = {"event": Event.objects.get(pk=event_id)}
    # date = {"date": Date.objects.get(pk=event_id)}
    return render(request, "phenomena/single.html", event)

def locations(request):
    all_locations = {"locations": Location.objects.all()}
    return render(request, "phenomena/locations.html", all_locations)

def country(request, country):
    req_location = Location.objects.get(location=country)
    event_location = {"events": Event.objects.filter(location__location=req_location)}
    return render(request, "phenomena/country.html", event_location)

def dates(request):
    all_dates = {"dates": Date.objects.all()}
    return render(request, "phenomena/dates.html", all_dates)


# def specificdate (request, specificdate):
#     req_date = Date.objects.get(date=specificdate)
#     event_date = {"dates": Date.objects.filter(date__date=req_date)}
#     return render(request, "phenomena/specificdate.html", event_date)





    

# def index(request):
#     return HttpResponse("testing testing, 1,2,3")
# # Create your views here.


#remember when changing from http response to render, it needs to be a dictionary

phenomena/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{%block title%}{%endblock%}</title>
    {%block style%}{%endblock%}
</head>
<nav id="nav-bar">
    <div id="nav-link"><a href="{%url 'index'%}">Events</a></div>
    <div id="nav-link"><a href="{%url 'locations'%}">Locations</a></div>
    <div id="nav-link"><a href="{%url 'dates'%}">Dates</a></div>
</nav>
<body>
    {%block content%}{%endblock%}
</body>
</html>

phenomena/templates/phenomena/country.html
{% extends "base.html" %}
{% load static %}
{% block title %}Phenomena{% endblock %}
{% block content %}
{% block style %} <link rel="stylesheet" href="{% static 'phenomena/style.css' %}"> {% endblock %}

<h2 id="country-heading"> The following events happened in this country:</h2>
<ul id="country-list">
    {% for event in events %}

    <li><a href="{% url 'single' event.id %}">{{ event.name }}</a></li>

</ul>
        
    {% empty %}
        <li>No events in this country!</li>
    {% endfor %}


    {% endblock %}

phenomena/templates/phenomena/dates.html
{% extends "base.html" %}
{% load static %} 
{% block content %}
{% block style %} <link rel="stylesheet" href="{% static 'phenomena/style.css' %}"> {% endblock %}

<h2 id="dates-heading">Unexplained events took place on the following dates: </h2>

<ul id=date-list>
    {% for date in dates %}
    <li>{{ date.date }}</li> 

    {% empty %}
    <li>No events to show</li>
    {% endfor %}
</ul>

{% endblock %}

phenomena/templates/phenomena/index.html
{%extends "base.html"%}
{%load static%}
{%block style%}<link rel="stylesheet" href="{%static 'phenomena/style.css'%}">{%endblock%}
{%block title%}Phenomena{%endblock%}
{%block content%}

<div id="indexTitle">The Pathfinder Project Presents</div>

<div id="indexHeading"> Unexplained Events:</div>

{% for event in events %}
<div><a id="indexEvents" href="{%url 'single' event.id%}">{{event.name}}</a></div>

{%empty%}
    No Events to show
{%endfor%}

{%endblock%}

phenomena/templates/phenomena/locations.html
{% extends "base.html" %}
{% load static %} 
{% block title %}Phenomena{% endblock %}
{% block content %}
{% block style %} <link rel="stylesheet" href="{% static 'phenomena/style.css' %}"> {% endblock %}

<h2 id="location-heading"> Unexplained events have taken place in the following locations: </h2>
<ul id="location-list">
    {% for location in locations %}
  <li><a href="{% url 'country' location.location %}">{{ location.location }}</a></li> 

    {% empty %}
    <li>No events to show</li>
    {% endfor %}
</ul>

{% endblock %}

phenomena/templates/phenomena/single.html
{% extends "base.html" %}
{% load static %} 
{% block style %} <link rel="stylesheet" href="{% static 'phenomena/style.css' %}"> {% endblock %}
{% block title %}Phenomena{% endblock %}
{% block content %}

<h1 id="singleHeading">{{event.name}}</h1>
<p id="singleParagraph">{{ event.info }}</p>

{% for date in event.date_set.all %}
<div id="singleDate"><p> Occurance:  {{ date }}</p></div>
{% endfor %}

{% for location in event.location_set.all %}
    <div id="single-location">Location: {{ location }}</div>
{% endfor %}
{% endblock %}